[package]
name = "par-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
description = "Core library for par-rs (config, session, compose, runner)"

[dependencies]

